### ISSUE TITLE
Sprint 6 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#101]
## Prioritized Themes

* [AUTH0 DASHBOARD] _Drive the dashboard infrastructure to DONE-DONE_ 
   - [ ] Development of core Dashboard [functionality](https://github.com/mozilla-iam/sso-dashboard/projects/1)
   - [x] #99 SSO Dashboard Development Environment 
   - [ ] #65 Fix workaround for adding new emails to be compatible with SSO dashboard
   - [ ]  #78 Production Deployment of SSO Dashboard 
   - [ ]  #83 Create Cloudformation to Deploy Multi-Region sso.dashboard
   - [x]  #84 Vanity urls served by sso.mozilla.com
* [AUTH0 DASHBOARD]_UI Development_ 
   - [x] #53 SSO Dashboard UX/UI - Design
   - [x] #92 Request Open Design Support for Icons 
   - [x]  #93  SSO Session Log in/Log out UX Update [Auth0 Lock]
   - [x] #103 SSO Dashboard Implement initial version of UI design
   - [x] #106 SSO Dashboard Fail Page
   - [x] #105 SSO Dashboard App Icons
   - [x] #109 SSO Dashboard Log Out Successful UI
   * Acceptance Criteria
      * Peer review to ensure work fits with Mozilla's webdev practices
      * Involve @m-branson in testing to ensure design was implemented properly
      * Cross-browser and cross-devices testing (Hi @viorelaioia !)
* [[LDAP INTEGRATION - MOZ](https://github.com/mozilla/iam-project-backlog/issues/107)] 
   * Change Integration Service ([CIS](https://github.com/mozilla-iam/cis/issues)): _A user profile goes into the Stream is validated and versioned in a persistent storage_
      - [x] #51 (LDAP Integration) Technical design on CIS
      - [ ] [Grant AWS IAM access to devs](https://github.com/mozilla-iam/cis/issues/5)
      - [ ] [Document starting point for developers](https://github.com/mozilla-iam/cis/issues/4)
      - [x] [Create object factories for testing](https://github.com/mozilla-iam/cis/issues/3) 
      - [ ] [Setup readthedocs for project documentation](https://github.com/mozilla-iam/cis/issues/1)
      - [ ] #117 Write user profile to stream (From Mozillians.org)
      - [ ] #118 Sign message with Mozillians KMS Key
      - [ ] #119: Setup Kinesis input stream
      - [ ] #120: Setup CI
      - [ ]  [Write Stream Processor Validator](https://github.com/mozilla-iam/cis/issues/7)
      - [ ] #121 Write Stream Processor Identity Vault Connector
      - [ ] #122 Setup Identity Vault
      - [ ] #114 Write Stream Processor Identity Driver Connector for Auth0
      - [ ] #124 AWS Monitoring/Metrics
      - [ ] #116 RP Handle new group information
      * Acceptance Criteria
         * A valid user profile is processed
         * An invalid user profile is rejected
         * An existing user profile is updated 
   - [x] #102 Functional view on Q2 OKR: A mocked volunteer Mozillians.org profile which was provisioned to LDAP via CIS is retrieved through Auth0
      * Validate functional view and stories
      * Grooming
- [ ] #104 Move Auth0 testrp from delegation endpoint to silent authentication for session management
* [MOZILLIANS.ORG]: Product maintenance to prepare infrastructure migration_
   - [ ] API V1 removal https://github.com/mozilla/parsys/issues/71
   - [ ] ElasticSearch security upgrade https://github.com/mozilla/parsys/issues/116
   - [ ] Increase quality in geographic search results (e.g. Berlin)
   - [ ] Send mozillians.org group & profile changes and events to mozdef (https://bugzilla.mozilla.org/show_bug.cgi?id=1354630)
* [INFRASTRUCTURE], including Hardening
   - [ ] Connect auditd to mozdef
   - [ ] Continue/wrap up other pending hardening work, see https://github.com/mozilla/parsys/issues/73 (meta issue)
   - [ ] Buy reserved instances
   - [ ]  Migrate Mozillians.org infrastructure: _set up a DEV instance_
   - [ ] Support Mozillians.org pentesting (multi-sprint accompanying activity), [Bug 1357743](https://bugzilla.mozilla.org/show_bug.cgi?id=1357743) and https://github.com/mozilla/iam-project-backlog/issues/94
* [AUTH0 LOCK] _Prototype new technology stack
   - [x] https://github.com/mozilla/parsys/issues/91
   - [ ] #67 
   - [x] #71 
   - [ ] Decide on technology stack for Front-end and AWS Lambda (backend)
   - [ ] Create backlog items
* [TEST AUTOMATION] 
   - [ ] #33 Session Testing
   - [ ] #100 Test Improvement
* UX Design: 
   - [ ] #67 Mozillians.org Sign Up UI design
   - [x] #91 Tech Review of Mozillians Profile Settings
   - [ ] #96 SSO Dashboard Alert/Notification UI Design

## For mental sanity: Other InfoSec Work
- [ ] #79 [SECOND OPINION] _PoC for end-to-end testing_ and _productionalizing implementation
* Any (opportunistic) OKTA/Auth0 property migration (?) 

## For mental sanity: Other ParSys Work
* Reps: _product maintenance_
   - [ ] Finalize celery upgrade
   - [ ] Move Reps to Mozillians.org API V2 (https://github.com/mozilla/parsys/issues/100)
* Discourse:
   - [ ] Pick up work on multiple email support_ https://github.com/mozilla/parsys/issues/74
   - [ ] Advance test automation
* [CoSS](https://github.com/mozilla/coss/)
   - [ ] Passwordless login to CoSS
   - [ ] Staff LDAP login to CoSS

## Unplanned Scope
> **Note:** please add any unplanned scope that you worked on here.

# Out of Scope / Later Items
Themes which are not **yet** slated for delivery
* **(blocked)** RP Migration / IAM SSO Property [Migration Plan](https://docs.google.com/spreadsheets/d/1VLwh2A9qbaRqByj7BYbnziWQLL_DdjemAiwT4_0OebE/edit): Requires a working SSO Dashboard

# Logistics
* 01 MAY: Public holiday in most parts of Europe
* Out of Office: @hmitsch on Friday
* CoSS share: @johngian and @akatsoulas plan to work 20% on CoSS this sprint
* Alignment sessions: 
   * *Technical:* This THU, CET-friendly
   * *Grooming*: Next THU, PST-friendly

**Comment by tyearns** [comment]
**Sprint Board Management Guidelines (Proposed)**
   Individual story-cards should be created and maintained within the Master Sprint Board (iam-project-backlog) for all project activities:
   * The "Master" board will contain only in-scope story cards for the work to be completed within each sprint (as opposed to the Sprint Goal story card)
      * Any stories that cannot be worked on within the active sprint should be backlogged
   * The Sprint Goal story card may outline the scope of work intended to be undertaken at the beginning of each sprint however it needn't be updated or managed during the sprint
   * Progress updates, notes/decisions, and any technical/functional details should be reflected within each of the story cards  
      * Each story card must contain  a description of the work to be completed, and any/all relevant links to external references where applicable
      * Story card updates should be submitted by EOD every Tuesday
      * Each story card **MUST** be assigned a work-stream label _(ex:**[WORKSTREAM]**)_
 * Spikes (**"Experiments"**) - Discovery efforts should be tracked as a story card, using the **":SPIKE:"** label, to reflect research efforts - expected outcome is direction and/or solution alternatives to be used during design discussion (POC's)
 * Chores - The **":CHORE:"** label will be assigned to story cards that reference external reports/queues (Bugzilla, others) for tech-debt related activities currently in-progress or completed
      * Any team member may contribute to this card as needed
      * Single point of reference for tech debt activities that don't have a story card in the sprint board.

**Comment by andrewkrug** [comment]
https://github.com/mozilla/iam-project-backlog/issues/106 Adding fail page story

**Comment by andrewkrug** [comment]
Adding ICON story https://github.com/mozilla/iam-project-backlog/issues/106

**Comment by mbransn** [comment]
Updated UX Design to include SSO fail page #106, SSO Icons #105 and Mozillians.org profile settings tech alignment #91.

**Comment by andrewkrug** [comment]
Sprint goal card brought in line with reality.  Up to date regarding dashboard work.  4/24/17

**Comment by mbransn** [comment]
Added #109 to align UX goal with current SSO dashboard progress.

**Comment by gdestuynder** [comment]
we're at sprint 11, closing
