### ISSUE TITLE
Identity Management / Mozillians.org Integration - Parent

### ISSUE THREAD

**Issue by tyearns** [mozilla-iam/iam-project-backlog#107]
**Parent story for all story cards associated with the LDAP/Mozillians.org Integration workstream.**

   - [x] #3 (L) Auth0 enriched profiles (formerly acct linking)
   - [x] #50 (LDAP Integration) Define how Auth0-Mozillians.org synchronization will work
   - [x] #5 (L) Business Engineering: Automatic LDAP attribute refresh  
   - [x] #6 (L) Automatic Mozillians.org group refresh
   - [x] #31 Ensure LDAP groups get reflected on auth0 side periodically (without requiring an LDAP login)
   - [ ] <del>#42 (LDAP Integration) SQL LDAP POC --> post Q2</del>
   - [x] #49 (LDAP Integration) Realize an agreed upon 'User Profile' (aka LDAP schema) 
   - [x] #57 User profile synchronization service between LDAP and Auth0 
   * Change Integration Service ([CIS](https://github.com/mozilla-iam/cis/issues)): _A user profile goes into the Stream is validated and versioned in a persistent storage_
      - [x] #51 (LDAP Integration) Technical design on CIS
      - [x] [Grant AWS IAM access to devs](https://github.com/mozilla-iam/cis/issues/5)
      - [x] [Document starting point for developers](https://github.com/mozilla-iam/cis/issues/4)
      - [x] [Create object factories for testing](https://github.com/mozilla-iam/cis/issues/3) 
      - [x] [Setup readthedocs for project documentation](https://github.com/mozilla-iam/cis/issues/1)
      - [x] #117 Write user profile to stream (From Mozillians.org)
      - [ ] #118 Sign message with Mozillians KMS Key
      - [x] #119: Setup Kinesis input stream
      - [x] #120: Setup CI
      - [x]  [Write Stream Processor Validator](https://github.com/mozilla-iam/cis/issues/7)
      - [x] #121 Write Stream Processor Identity Vault Connector
      - [x] #122 Setup Identity Vault
      - [x] #114 Write Stream Processor Identity Driver Connector for Auth0
      - [ ] #124 AWS Monitoring/Metrics
      - [ ] #116 RP Handle new group information
   * Acceptance Criteria
      * A valid user profile is processed
      * An invalid user profile is rejected
      * An existing user profile is updated  
   - [ ] #72 Employee account handling automation --> post Q2
   - [ ] #91 Tech Review of Mozillians Profile Settings 
   - [ ] #102 Functional view on Q2 OKR: A mocked volunteer Mozillians.org profile which was provisioned to LDAP via CIS is retrieved through Auth0

**Comment by gdestuynder** [comment]
we now track work in https://github.com/mozilla-iam/iam-project-backlog/issues/173 though this is a good future reference (this comment will back reference for the purpose of being able to find this back)
