### ISSUE TITLE
Sprint 7 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#127]
### Summary

1. [AUTH0 DASHBOARD] Post-launch: _The Cursed Trinity_ 
1. [RP Cutover] Migrate sprint 7 batch
1. [LDAP INTEGRATION - MOZ] Change Integration Service ([CIS](https://github.com/mozilla-iam/cis/issues)): _A user profile goes into the Stream is validated and versioned in a persistent storage_
1. [MOZILLIANS.ORG]: _Product maintenance to prepare infrastructure migration_ and _hardening_
1. Test automation
1. UX Design
 
### Details
* [AUTH0 DASHBOARD] Post-launch: _The Cursed Trinity_ 
   - [ ] (bugfix) Cannot login to discourse from sso dashboard if the ldap is not associated with a discourse account https://github.com/mozilla-iam/sso-dashboard-configuration/issues/22
   - [ ] (bugfix) User remains logged in to The Hub after logging out from both The Hub and SSO dashboard https://github.com/mozilla-iam/sso-dashboard-configuration/issues/23
   - [ ] (bugfix) User can access Egencia account by url, after logging out from both Egencia and SSO dashboard  https://github.com/mozilla-iam/sso-dashboard-configuration/issues/24
   - [ ] (bugfix) Accessing SSO settings requires logging into mozillians.mozilla.org https://github.com/mozilla-iam/sso-dashboard/issues/102
   - [ ] (bugfix) App icons and app page requires scrolling, even on high-DPI monitors https://github.com/mozilla-iam/sso-dashboard/issues/101
   - [ ] (bugfix) **(Waiting for thinksmart)** thinksmart asks me to login twice https://github.com/mozilla-iam/sso-dashboard/issues/96
   - [ ] (bugfix) Mozillians doesn't work https://github.com/mozilla-iam/sso-dashboard-configuration/issues/16
   - [ ] maintenance
   - [ ] (enhancement) check the configuration repo
   - [ ] (enhancement) air.mozilla.org missing from dashboard https://github.com/mozilla-iam/sso-dashboard-configuration/issues/17
   - [ ] (enhancement) Run access-proxy in front of SSO dashboard (https://github.com/mozilla-iam/sso-dashboard/issues/107)
   - [x] (enhancement) add a link to the sso-dashboard github repo https://github.com/mozilla-iam/sso-dashboard/issues/103

* [RP Cutover] Migrate sprint 7 batch, [Migration Plan](https://docs.google.com/spreadsheets/d/1VLwh2A9qbaRqByj7BYbnziWQLL_DdjemAiwT4_0OebE/edit)
   - [ ] #130 Group 0 - Stage and Dev instances that are managed by IT or InfoSec
   - [ ] #131 Group 1 - Managed within IT (InfoSec, WebOps)

* [[LDAP INTEGRATION - MOZ](https://github.com/mozilla/iam-project-backlog/issues/107)] 
   * Change Integration Service ([CIS](https://github.com/mozilla-iam/cis/issues)): _A user profile goes into the Stream is validated and versioned in a persistent storage_
      - [x] [Grant AWS IAM access to devs](https://github.com/mozilla-iam/cis/issues/5)
      - [x] [Document starting point for developers](https://github.com/mozilla-iam/cis/issues/4)
      - [x] [Setup readthedocs for project documentation](https://github.com/mozilla-iam/cis/issues/1)
      - [ ] #117 Write user profile to stream (From Mozillians.org)
      - [ ] #118 Sign message with Mozillians KMS Key
      - [x] #119: Setup Kinesis input stream
      - [ ] #120: Setup CI
      - [ ]  [Write Stream Processor Validator](https://github.com/mozilla-iam/cis/issues/7)
      - [ ] #121 Write Stream Processor Identity Vault Connector
      - [x] #122 Setup Identity Vault
      - [ ] #114 Write Stream Processor Identity Driver Connector for Auth0
      - [x] #124 Define AWS Monitoring/Metrics
      - [ ] #116 RP Handle new group information
      * Acceptance Criteria
         * A valid user profile is processed
         * An invalid user profile is rejected
         * An existing user profile is updated 

* [MOZILLIANS.ORG]: _Product maintenance to prepare infrastructure migration_
   - [ ] ElasticSearch security upgrade https://github.com/mozilla/parsys/issues/116
   - [ ] Increase quality in geographic search results (e.g. Berlin)
   - [ ] Send mozillians.org group & profile changes and events to mozdef (https://bugzilla.mozilla.org/show_bug.cgi?id=1354630)

* [INFRASTRUCTURE], including Hardening
   - [ ] Connect auditd to mozdef
   - [ ] Continue/wrap up other pending hardening work, see https://github.com/mozilla/parsys/issues/73 (meta issue)
   - [ ] Buy reserved instances
   - [ ]  Migrate Mozillians.org infrastructure: _set up a DEV instance_
   - [ ] Support Mozillians.org pentesting (multi-sprint accompanying activity), [Bug 1357743](https://bugzilla.mozilla.org/show_bug.cgi?id=1357743) and https://github.com/mozilla/iam-project-backlog/issues/94

* [TEST AUTOMATION] 
   - [ ] Configure session testing tests to run in parsys jenkins instance #128

* UX Design: 
   - [ ] Mozillians.org Profile Editor UX v2 #113
   - [ ] Mozillians.org Brand/Sign Up UI iteration #125
   - [ ] SSO Dashboard UI enhancements
       - [ ] alert/notifications review & iteration #96

## For mental sanity: Other InfoSec Work
- [ ] #79 [SECOND OPINION] _PoC for end-to-end testing_ and _productionalizing_ implementation

## For mental sanity: Other ParSys Work
* [CoSS](https://github.com/mozilla/coss/)
   - [ ] _Priority:_ As a **Clubs Program Manager** I want to **create a program page with a theme** in order to create a program web presence (implementation detail: local user/pass).
   - [ ] _Best effort:_ As a **volunteer** I want to **register as a Club Captain** in order to become a volunteer leader (implementation detail: Auth0 and Mozilla CRM integrations).
* Discourse:
   - [ ] Pick up work on _multiple email support_ https://github.com/mozilla/parsys/issues/74
   - [ ] Advance test automation

## Unplanned Scope
> **Note:** please add any unplanned scope that you worked on here.

# Out of Scope / Later Items
Themes which are not **yet** slated for delivery
* SSO Dashboard improvements
   - [ ] Re-order apps in SSO view https://github.com/mozilla-iam/sso-dashboard/issues/104
   - [ ] UX: user favorites https://github.com/mozilla-iam/sso-dashboard/issues/92 / frequently used #98
* Get SSO Dashboard launch-ready for community
   - [ ] Implement low- and med-risk alert UI https://github.com/mozilla-iam/sso-dashboard/issues/130
* [AUTH0 LOCK] _Prototype new technology stack_
   - [ ] #67 
   - [ ] Decide on technology stack for Front-end and AWS Lambda (backend)
   - [ ] Create backlog items
* Move AirMo to 'hosted Auth0 Lock'

# Logistics
* Out of Office: @gene1wood out for 2 days next week, @m-branson out on May 12
* CoSS share: @akatsoulas plan to work with a focus on CoSS this sprint
* Alignment sessions: 
   * *Technical:* This THU, CET-friendly (*we will move it back by one hour from 9am PST to 10am PST, thank you European colleagues*)
   * *Grooming*: Next THU, PST-friendly

**Comment by andrewkrug** [comment]
@hmitsch  just noticed this for sso-dashboard never had an issue. (enhancement) check the configuration repo.  Do you know who's issue this is and what it means?

**Comment by hmitsch** [comment]
@andrewkrug yes, I hope I can explain.

You ask about the following acceptance criteria line:
> (enhancement) check the configuration repo

It means we should check these issues: https://github.com/mozilla-iam/sso-dashboard-configuration/issues and see if we can get stuff done.

May I suggest you have a look at the issues and we then decide if any of these is important enough to add it to the next sprint?
