### ISSUE TITLE
Sprint 8 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#142]
## Prioritized Themes
1. [LDAP INTEGRATION - MOZ] Change Integration Service ([CIS](https://github.com/mozilla-iam/cis/issues)): _Manually push data to the queue, validate and store to DynamoDB_
1. [MOZILLIANS.ORG]: _Finish the hardening/upgrade work_ (get all open issues closed)

### Details
1. [LDAP INTEGRATION - MOZ] Change Integration Service ([CIS](https://github.com/mozilla-iam/cis/issues)): _Manually push data to the queue, validate and store to DynamoDB_
      - [ ] #117 Write user profile to stream (From Mozillians.org)
      - [ ] #118 Sign message with Mozillians KMS Key
      - [ ] #120: Setup CI
      - [x]  [Write Stream Processor Validator](https://github.com/mozilla-iam/cis/issues/7)
      - [x] Use and validate new user profile: https://github.com/mozilla-iam/cis/issues/48
      - [ ] #121 Write Stream Processor Identity Vault Connector
      - [ ] #114 Write Stream Processor Identity Driver Connector for Auth0
      - [ ] #116 RP Handle new group information
      * Acceptance Criteria
         * A valid user profile is processed
         * An invalid user profile is rejected
         * An existing user profile is updated 
1. [MOZILLIANS.ORG]: _Finish the hardening/upgrade work_
   - [ ] Send mozillians.org group & profile changes and events to MozDef (https://github.com/mozilla/parsys/issues/99), (https://bugzilla.mozilla.org/show_bug.cgi?id=1354630)
   - [ ] ElasticSearch security upgrade https://github.com/mozilla/parsys/issues/116
   - [ ] Increase quality in geographic search results (e.g. Berlin)
   - [ ] Connect auditd to mozdef
   - [x] Continue/wrap up other pending hardening work, see https://github.com/mozilla/parsys/issues/73 (meta issue)
   - [x] Buy reserved instances
   - [x] Refactor S3 buckets https://github.com/mozilla-iam/mozilla-iam/issues/23
   - [x]  Migrate Mozillians.org infrastructure: _set up a DEV instance_
   - [x] Support Mozillians.org pentesting (multi-sprint accompanying activity), [Bug 1357743](https://bugzilla.mozilla.org/show_bug.cgi?id=1357743) and https://github.com/mozilla/iam-project-backlog/issues/94
1. Test automation: _Finish session testing work_ 
   - [x] #145
   - [x] #146
   - [ ] #147
1. [AUTH0 DASHBOARD] Last bit of pre All Hands cleanup
   - [ ] (enhancement) air.mozilla.org missing from dashboard https://github.com/mozilla-iam/sso-dashboard-configuration/issues/17
   - [ ] (bugfix) Run access-proxy in front of SSO dashboard (https://github.com/mozilla-iam/sso-dashboard/issues/107)
1. [RP Cutover] Migrate sprint 8 batch, [Migration Plan](https://docs.google.com/spreadsheets/d/1VLwh2A9qbaRqByj7BYbnziWQLL_DdjemAiwT4_0OebE/edit)
   - [ ] #130 Group 0 (in execution) - Stage and Dev instances that are managed by IT or InfoSec
   - [ ] #131 Group 1 (in requirements definition) - Managed within IT (InfoSec, WebOps)
1. [ ] #79 [SECOND OPINION] _PoC for end-to-end testing_ and _productionalizing_ implementation

## For mental sanity: Other ParSys Work
* [CoSS](https://github.com/mozilla/coss/) Sprint 8 https://github.com/mozilla/coss/issues/142
* Discourse:
   - [ ] Carry on revising _multiple email support_ PR based on review, https://github.com/mozilla/parsys/issues/74
   - [ ] Use silent authentication in discourse

## Unplanned Scope
**Note:** please add any unplanned scope that you worked on here.

## Out of Scope / Later Items
Themes which are not **yet** slated for delivery
* OIDC Library Improvements: https://github.com/mozilla/mozilla-django-oidc/issues/94
* Slack for Community access (@hmitsch currently in conversations with Jason Bradford)
* SSO Dashboard improvements
   - [ ] Re-order apps in SSO view https://github.com/mozilla-iam/sso-dashboard/issues/104
   - [ ] UX: user favorites https://github.com/mozilla-iam/sso-dashboard/issues/92 / frequently used #98
* Get SSO Dashboard launch-ready for community
   - [ ] Implement low- and med-risk alert UI https://github.com/mozilla-iam/sso-dashboard/issues/130
* [AUTH0 LOCK] _Prototype new technology stack_
   - [ ] #67 
   - [ ] Decide on technology stack for Front-end and AWS Lambda (backend)
   - [ ] Create backlog items
* Move AirMo to 'hosted Auth0 Lock'

## Logistics
* Out of Office: 25 MAY is a public holiday in Germany, 29 MAY is a public holiday in the US & UK
* CoSS share: @akatsoulas @comzeradd @m-branson  focus on CoSS this sprint
* Alignment sessions: 
   * *Technical:* This THU, semi-CET-friendly (*moved because of monthly Open Innovation All Hands*)
   * *Grooming*: Next THU, PST-friendly
