### ISSUE TITLE
Sprint 9 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#152]
## Prioritized Themes
1. [LDAP INTEGRATION - MOZ] Change Integration Service ([CIS](https://github.com/mozilla-iam/cis/issues)): _Manually push data to the queue, validate and store to DynamoDB_
1. [MOZILLIANS.ORG]: _Staging environment successfully migrated_

### Details
1. [LDAP INTEGRATION - MOZ] Change Integration Service ([CIS](https://github.com/mozilla-iam/cis/issues)): _Manually push data to the queue, validate and store to DynamoDB_
      - [x] #117 Write user profile to stream (From Mozillians.org)
      ~~- [ ] #118 Sign message with Mozillians KMS Key~~ ( Out of scope for OKR ) ( andrew wrote pykmssig )

      - [x] #120: Setup CI ( Done ) -- In Development only.
      - [x] #121 Write Stream Processor Identity Vault Connector ( Complete 100% )
      - [x] #114 Write Stream Processor Identity Driver Connector for Auth0 ( Complete 100% )
      - [ ] #116 RP Handle new group information ( In progress )
      * Acceptance Criteria
         * A valid user profile is processed ( Done )
         * An invalid user profile is rejected ( Done )
         * An existing user profile is updated  ( Done )
1. [MOZILLIANS.ORG]: _Staging environment successfully migrated_
   - [ ] Send mozillians.org group & profile changes and events to MozDef (https://github.com/mozilla/parsys/issues/99), (https://bugzilla.mozilla.org/show_bug.cgi?id=1354630)
   - [ ] ElasticSearch security upgrade https://github.com/mozilla/parsys/issues/116
   - [ ] Increase quality in geographic search results (e.g. Berlin), https://github.com/mozilla/parsys/issues/116
   - [ ] Connect auditd to mozdef
   - [ ] Create mozillians.org infrastructure https://github.com/mozilla/parsys/issues/119
1. OIDC Library Improvements: _Support prompt parameter none instead of the delegation endpoint_  https://github.com/mozilla/mozilla-django-oidc/issues/94
1. QA Engineering  
   - [ ] Mozillians.org search refactor (https://github.com/mozilla/parsys/issues/116): quality assurance
   - [x] Test automation: _Finish session testing work_ #147
1. [AUTH0 DASHBOARD] Last bit of pre All Hands cleanup
   - [x] (enhancement) air.mozilla.org missing from dashboard https://github.com/mozilla-iam/sso-dashboard-configuration/issues/17 ( Staged but not released )
   - [ ] (bugfix) Run access-proxy in front of SSO dashboard (https://github.com/mozilla-iam/sso-dashboard/issues/107)
1. [RP Cutover] Migrate sprint 8 batch, [Migration Plan](https://docs.google.com/spreadsheets/d/1VLwh2A9qbaRqByj7BYbnziWQLL_DdjemAiwT4_0OebE/edit)
   - [ ] #130 Group 0 (in execution) - Stage and Dev instances that are managed by IT or InfoSec (6 of 8 completed)
   - [ ] #131 Group 1 (in requirements definition) - Managed within IT (InfoSec, WebOps)
1. [ ] #79 [SECOND OPINION] _PoC for end-to-end testing_ and _productionalizing_ implementation
1. [DISCOURSE] *Sync groups from Auth0*
   - [x] Add proper session management https://github.com/mozilla/parsys/issues/135
   - [ ] Query groups before sending email https://github.com/mozilla/parsys/issues/151
   - [ ] Carry on revising _multiple email support_ PR based on review, https://github.com/mozilla/parsys/issues/74

## For mental sanity: Other ParSys Work
* [CoSS](https://github.com/mozilla/coss/) Sprint 9 https://github.com/mozilla/coss/issues/165

## Unplanned Scope
**Note:** please add any unplanned scope that you worked on here.

## Out of Scope / Later Items
Themes which are not **yet** slated for delivery
* Slack for Community access (@hmitsch currently in conversations with Jason Bradford)
* SSO Dashboard improvements
   - UX: user favorites https://github.com/mozilla-iam/sso-dashboard/issues/92 / frequently used #98
   - Fix SSO with ParSys properties
* Get SSO Dashboard launch-ready for community
   - Implement low- and med-risk alert UI https://github.com/mozilla-iam/sso-dashboard/issues/130
* [AUTH0 LOCK] _Prototype new technology stack_
   - Sign Up UI design #67 
   - Decide on technology stack for Front-end and AWS Lambda (backend)
   - Create backlog items
* Move AirMo to 'hosted Auth0 Lock'

## Logistics
* Out of Office: MON 05 JUN is a public holiday in Germany, @viorelaioia our for vacation in first half of the sprint
* CoSS share: @comzeradd @m-branson focus mostly on CoSS, @akatsoulas supports

**Comment by tyearns** [comment]
Hey folks, kindly take a moment to update your story cards so as to reflect the current status today.
