### ISSUE TITLE
Sprint 10 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#159]
## Prioritized Themes
1. [LDAP INTEGRATION - MOZ] Q2 OKR (All Hands Demo): _Clean up, payback outstanding debt_
1. [MOZILLIANS.ORG]: _PROD migration on 22 JUN 2017_

### Details
1. [LDAP INTEGRATION - MOZ] Change Integration Service ([CIS](https://github.com/mozilla-iam/cis/issues)): _Clean up, payback outstanding debt__
      - [ ] #116 RP Handle new group information ( In progress )
      - [x] Demo Video https://github.com/mozilla/iam-project-backlog/issues/157
      - [ ] Remove Hard Coded Partition Key https://github.com/mozilla-iam/cis/issues/54
      - [ ] Remove Duplicate Code https://github.com/mozilla-iam/cis/issues/55
      - [ ] Move Logging Utils to CIS Core https://github.com/mozilla-iam/cis/issues/53
1. [MOZILLIANS.ORG]: _PROD migration on 22 JUN 2017_
   - [x] Send mozillians.org group & profile changes and events to MozDef (https://github.com/mozilla/parsys/issues/99), (https://bugzilla.mozilla.org/show_bug.cgi?id=1354630)
   - [x] ElasticSearch security upgrade https://github.com/mozilla/parsys/issues/116
   - [x] Increase quality in geographic search results (e.g. Berlin), https://github.com/mozilla/parsys/issues/116
   - [ ] Connect auditd to mozdef
   - [x] Create mozillians.org infrastructure https://github.com/mozilla/parsys/issues/119
   - [x] CI for mozillians.org https://github.com/mozilla/parsys/issues/176
   - [x] Move mozillians.org DNS to partinfra AWS https://github.com/mozilla/parsys/issues/172
   - [x] Get things from webops https://github.com/mozilla/parsys/issues/170 https://github.com/mozilla/parsys/issues/173 https://bugzilla.mozilla.org/show_bug.cgi?id=1373236
   - [x] Get change review and do the migration
1. [AUTH0 DASHBOARD] Last bit of pre All Hands cleanup
   - ( Staged but not released ) [x] (enhancement) air.mozilla.org missing from dashboard https://github.com/mozilla-iam/sso-dashboard-configuration/issues/17 
1. [RP Cutover] Migrate sprint batch, [Migration Plan](https://docs.google.com/spreadsheets/d/1VLwh2A9qbaRqByj7BYbnziWQLL_DdjemAiwT4_0OebE/edit)
   - [ ] #130 Group 0 (in execution) - Stage and Dev instances that are managed by IT or InfoSec (6 of 8 completed)
   - [ ] #131 Group 1 (in requirements definition) - Managed within IT (InfoSec, WebOps)
1. [ ] #79 [SECOND OPINION] _PoC for end-to-end testing_ and _productionalizing_ implementation

## For mental sanity: Other InfoSec Work

Andrew:
1.  Planning for aws incident response 2-hour session at all hands
2. Write enhanced IR Escalation / Procedure for AWS @ Mozilla
3. Recruit for the AWS CTF

## For mental sanity: Other ParSys Work
1. [CoSS](https://github.com/mozilla/coss/) Sprint 10 https://github.com/mozilla/coss/issues/189
1. QA Engineering  
   - [x] [Mozillians.org search refactor](https://github.com/mozilla/parsys/issues/116): Update Mozillians automated tests according to search refactor changes https://github.com/mozilla/parsys/issues/157
   - [x] (Test Automation)(Discourse) Implement test case "Verify that the user is able to create a new topic" https://github.com/mozilla/parsys/issues/159
   - [x] (Test Automation)(Discourse) Implement test case "Verify that a user can go through the existing Categories" https://github.com/mozilla/parsys/issues/160
1. [DISCOURSE] *All the things*
   - [ ] Query groups before sending email https://github.com/mozilla/parsys/issues/151 [_currently writing tests_ ]
   - [ ] Carry on revising _multiple email support_ PR based on review, https://github.com/mozilla/parsys/issues/74 [_phase 1 closer to being merged upstream, but not there yet_ ]
   - [ ] Automatically set-up email-in addresses based on category slug https://github.com/mozilla/parsys/issues/35 \[_blocked by https://github.com/mozilla/parsys/issues/6_ ]
   - [ ] Email-in thread with same title does nothing https://github.com/mozilla/parsys/issues/101
   - [x] Fix incorrect threading with email-in replies https://github.com/mozilla/parsys/issues/83
1. [ ] [Reps] Review Contributors pending PRs https://github.com/mozilla/parsys/issues/102
1. [x] [Mozillians] [Change of URL slug for TechSpeaker Mozillians group](https://bugzilla.mozilla.org/show_bug.cgi?id=1370739)
1. Mentor bugs
   * [Create a view with all vouched mozillians](https://bugzilla.mozilla.org/show_bug.cgi?id=847911)

## Unplanned Scope
**Note:** please add any unplanned scope that you worked on here.
* [ ] [Bug 1373894](https://bugzilla.mozilla.org/show_bug.cgi?id=1373894): Potential XSS in Mozillians.org
* [x] [Bug 1374307](https://bugzilla.mozilla.org/show_bug.cgi?id=1374307): Auth0 auth loop when trying to add secondary email via Mozillians.org
* [ ] Automate client testing in auth0-deploy CI, include SAML clients https://github.com/mozilla/iam-project-backlog/issues/162 
* [x] [Bug 1376626](https://bugzilla.mozilla.org/show_bug.cgi?id=1376626) Extra whitespace before comma separating city and country
* [x] [Bug 1376583](https://bugzilla.mozilla.org/show_bug.cgi?id=1376583) https://www.mozillians.org returns an HTTP 503 (**post mortem**)
* [x] [Bug 1163927](https://bugzilla.mozilla.org/show_bug.cgi?id=1163927) Autocomplete city, region and country based on longitude and latitude (**post mortem**)
* [ ] [Bug 1376416 mozillians.allizom.org and mozillians-dev.allizom.org  are unreachable - 403 forbidden](https://bugzilla.mozilla.org/show_bug.cgi?id=1376416)
* [x] Add **Install Nightly** alerts to Auth0 Lock
* [x] Add **Install Nightly** alert to SSO Dashboard (https://github.com/mozilla-iam/sso-dashboard/pull/139)

## Out of Scope / Later Items
Themes which are not **yet** slated for delivery
* [SSO Dashboard] (bugfix) Run access-proxy in front of SSO dashboard (https://github.com/mozilla-iam/sso-dashboard/issues/107)
* Slack for Community access (next iteration of the current manual _NDA Pilot_)
* Move AirMo to 'hosted Auth0 Lock'
* SSO Dashboard improvements
   - UX: user favorites https://github.com/mozilla-iam/sso-dashboard/issues/92 / frequently used #98
   - Fix SSO with ParSys properties
* Get SSO Dashboard launch-ready for community
   - Implement low- and med-risk alert UI https://github.com/mozilla-iam/sso-dashboard/issues/130
* [AUTH0 LOCK] _Prototype new technology stack_
   - Sign Up UI design #67 
   - Decide on technology stack for Front-end and AWS Lambda (backend)
   - Create backlog items

## Logistics
* Out of Office
   * THU JUN 15 is a public holiday in Bavaria so @hmitsch is off
   * @viorelaioia off from JUN 21-23
   * All Hands week JUN 26-30, so we have to improvise and/or drop our *Sprint Review*
* CoSS share: @comzeradd @m-branson focus mostly on CoSS, @akatsoulas supports
