### ISSUE TITLE
Sprints 2017Q3 (Infosec)

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#173]
## 2017Q3 OKRs related to Infosec and IAM
See roadmap: https://app.productplan.com/RdSq8HT2

1. Objective: Migrate all RPs from Okta to Auth0
2. Objective: Ability to access AWS using SSO
3. Objective: Support security alerts for users in the SSO Dashboard
4. Objective: Ensure community users can leverage Mozillians groups in relying parties utilizing Auth0
5. Objective: Ability for CLI programs to authenticate using Auth0
6. Objective: MoCo users can easily share GDocs with the community

## Known current issues
- **Blocker** None
- **Slowdown** Working on CIS in prod (Objective 4)

#  Sprint 12 *(2017-07-24 to 2017-08-04)*
- [ ] RP Cutover Group 1 (migration from Okta to Auth0 SSO, see also [cut over verification link](https://github.com/mozilla-iam/sso-dashboard-configuration/blob/master/apps.yml)) (@jdow)
  - [x] Group 0 (stage/dev instances managed by IT/Infosec)
  - [x] Group 1 (all managed by IT) #131 
  - [x] Group 2 (Vendor support required, high visibility/risk) #132
  - [ ] Group 3 (Cutover coordinated independently) #133 
  - [ ] Decom RPs that won't migrate #61
- [ ] Accommodate Auth0 OIDC Conformant mode requirements (@jdow)
  - [x] Biztera compatibility #170
  - [ ] Migrate all RPs to full OIDC conformant mode #171
- [ ] SSH Federated Access (1+ sprint) (@gdestuynder)
  - [x] Brainstorm compatibility with AWS CLI w/ Gene
  - [ ] Finalize project documentation (https://mana.mozilla.org/wiki/display/SECURITY/Auth0+and+SSH)
  - [x] POC Pam JIT user provisioning
  - [ ] POC Client-side 
  - [ ] POC Server-side
  - [ ] POC IT Deploy with original groups
- [ ] "Second Opinion" (@gene1wood)
  - [x] Detailed design
  - [x] POC
  - [ ] Productionalize
- [x] CIS in production
  - [x] Event format specification document for publisher https://github.com/mozilla-iam/cis/issues/66 (@andrewkrug @gdestuynder)
  - [x] Cross account role permission for CIS prod between mozillians.org and infosec prod (This needs Parsys + Infosec coordination @hmitsch @andrewkrug )
  - [x] Create production KMS key for event signing (@gene1wood @andrewkrug)

# Sprint 13 *(2017-08-07 to 2017-08-18)*
***Insert multi-sprint items from previous sprint here***
- [ ] Workday to CIS integration (@andrewkrug)
  - [ ] Brainstorm design using reports with @jdow and @gdestuynder
  - [ ] Parser and stream publisher for Workday
  - [ ] Validation plugin for Workday groups
- [ ] AWS Federated access (@gene1wood)
  - [x] POC web federated access  (w/ @andrewkrug)
  - [x] Brainstorm CLI design with @gdestuynder
  - [ ] POC CLI federated access
  - [ ] Implement web/CLI federated access for Infosec
  - [ ] Implement web/CLI federated access with Nubis
  - [ ] Socialize/document
- [ ] Dashboard alerting (@andrewkrug)
  - Depends on: UX and web-design (Nikos/Megan)
  - [ ] Remove nightly download alert
  - [ ] Discuss UX implementation
  - [ ] Discuss architecture
  - [ ] Get alerts from MozDef

# Sprint 14 *(2017-08-21 to 2017-09-01)*
- [ ] Functional and technical refinements ("pay tech debt")
  - [ ] Pre-plan LDAP to CIS connector (publisher) @jdow @andrewkrug @gdestuynder @floatingatoll  (FYI upcoming meeting plans)

# Sprint 15 *(2017-09-04 to 2017-09-15)*

# Sprint 16 *(2017-09-18 to 2017-09-29)*

# 2017Q4 cut over - Sprint 17 *2017-10-02 onwards*

# Backlog (on the short-list)
- [ ] Automated CI RP testing #162 
- [ ] CIS to G-Suite connector (identity driver) - G-Suite document sharing w/ Mozillians.org group (newly proposed OKR from Henrik)
- [ ] LDAP to CIS connector (publisher) 
- [ ] CIS to LDAP connector (identity driver) #115
- [ ] API Key support on behalf of RP's
- [ ] Mozillians.org infra security audit (@gene1wood to check story card, @claudijd also has info)

# Meta
- [SmartSheet link](https://app.smartsheet.com/b/home?lx=9nvThlXQdImtxUmdlWJ-hw)
- [IAM Project page](https://mana.mozilla.org/wiki/display/SECURITY/IAM)
- [IAM OKR Roadmap](https://app.productplan.com/RdSq8HT2)
- [ICEBOXed issues](https://github.com/mozilla-iam/iam-project-backlog/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+label%3AICEBOX)
- [BACKLOGed issues](https://github.com/mozilla-iam/iam-project-backlog/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+label%3ABACKLOG)
- PTOs
  - kang: in France/remote until sep 12
  - kang: PTO 7 aug to 10 aug + 14, 15 (approx 1.1 week currently planned)
  - andrew: approx 1 week in August ( last week )
  - andrew: approx 2 week in September ( travel but avail )
