### ISSUE TITLE
Sprint 13 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#183]
## Prioritized Themes
1. RP Cutovers, Sprint 13 bit
1. IAM Q2 OKR _PROD transition_ (_As a Mozilla Rep, I can access a specific Discourse category_) 
1. Workday integration: Embark on technical design journey
1. Mozillians.org Infrastructure and Application _debt repayment_

### Details
1. RP Cutover 
    - Migration from Okta to Auth0 SSO, see [cut over verification link](https://github.com/mozilla-iam/sso-dashboard-configuration/blob/master/apps.yml)
    - [Migration Plan](https://docs.google.com/spreadsheets/d/1VLwh2A9qbaRqByj7BYbnziWQLL_DdjemAiwT4_0OebE/edit)
    - [ ] Group 3 (Cutover coordinated independently) #133 
    - [ ] Decom RPs that won't migrate #61
1. _Q2 OKR PROD transition_
    - [ ] Merge demo functionality of CIS to mozillians.org
    - [ ] RP Handle new group information #116 (In progress)
    - [ ] Filter users interacted with https://github.com/mozilla-iam/cis/issues/5
    - [ ] Moz/CIS integration #107 (in progress)
    - [ ] CIS clean-up activities: #118, #124, Back-up/recovery of dynamo
    - [ ] Event format specification document for publisher (@andrewkrug @gdestuynder)
    - [ ] Cross account role permission for CIS prod between mozillians.org and infosec prod
    - [ ] Create production KMS key for event signing (@gene1wood @andrewkrug)
1. Workday to CIS integration
   - [ ] Brainstorm design using reports with @jdow and @gdestuynder
   - [ ] Parser and stream publisher for Workday
   - [ ] Validation plugin for Workday groups
1. Mozillians.org  _Infrastructure Cleanup_
   - [ ] Celery monitoring for reps/mozillians https://github.com/mozilla/parsys/issues/214
   - [ ] Fix mozillians.org S3 permissions https://github.com/mozilla/parsys/issues/134 https://github.com/mozilla/parsys/issues/191
   - [ ] Add cdn to mozillians media https://github.com/mozilla/parsys/issues/189
   - [ ] Work on open issues from [Mozillians.org Penetration Test](https://docs.google.com/document/d/19xD3UlDgb_vQJYVX0g3pvqfg1a3O6HjIsnvnC2vg-kI/edit)
    - [ ] [MOZILLIANS.ORG] Connect auditd to mozdef https://github.com/mozilla/parsys/issues/93
https://github.com/mozilla/parsys/issues/158
1. Mozillians.org _Application Cleanup_
   - [ ] Mozillians.org repo/Github org (debt) cleanup
   - [ ] Celery upgrade to version 4 for Mozillians https://github.com/mozilla/parsys/issues/210
1. QA Engineering
   - [ ] Have login tests implemented for all remaining RPs (13) that have LDAP login available: #184 , #185 , #186 , #187 , #188 , #189 , #190 , #191 , #192 , #193 , #194 , #195 , #196 .  
   - [ ] Automate client testing in auth0-deploy CI, include SAML clients https://github.com/mozilla/iam-project-backlog/issues/162
1. [SSO Dashboard] Launch for Communities
   - [x] Communicate the publicly available Dashboard widely: Discourse, various Telegram Channels, ~mailto all Mozillians (via Salesforce Marketing Cloud)~, Mozilla Reps
      - **DONE**
      - https://discourse.mozilla.org/t/cross-post-opening-the-sso-dashboard-to-mozilla-communities/17965
      - https://discourse.mozilla.org/t/x-post-opening-the-sso-dashboard-to-mozilla-communities/17964
      - https://discourse.mozilla.org/t/opening-the-sso-dashboard-to-mozilla-communities/17963
1. Auth0 Proxy for Community Analytics
   - [x] @gdestuynder to participate in a meeting with Bitergia next week

## For mental sanity: Other InfoSec Work
1. Accommodate Auth0 OIDC Conformant mode requirements #171
    - [ ] Create a list of RPs to decide next steps (test, coordinate with owners, switchover)
1. "Second Opinion" #79 
    - [ ] Productionalize
1. SSH Federated Access (multi-sprint) #169 
    - [ ] Finalize project documentation (https://mana.mozilla.org/wiki/display/SECURITY/Auth0+and+SSH)
    - [ ] POC Client-side 
    - [ ] POC Server-side
    - [ ] POC IT Deploy with original groups

## For mental sanity: Other ParSys Work
1. [ ] [CoSS](https://github.com/mozilla/coss/) Sprint 13 https://github.com/mozilla/coss/issues/244
1. [ ] [Discourse] https://github.com/mozilla/discourse/milestone/2
1. [ ] [Bug 138342](https://bugzilla.mozilla.org/show_bug.cgi?id=1383642) - OVH servers are down
1. [ ] Kick off Kubernetes pilot project

## Unplanned Scope
**Note:** please add any unplanned scope that you worked on here.
* [ ] [SSO Dashboard] Bug: Passwordless allows you to land in non-ssl routes https://github.com/mozilla-iam/sso-dashboard/issues/156
* [ ] [SSO Dashboard] Fetch user full name from mozillians.org https://github.com/mozilla-iam/sso-dashboard/issues/158

## Out of Scope / Later Items
Themes which are not **yet** slated for delivery
* Mozillians.org Binary search: get it to DONE-DONE
* [Fix bug 1201027] Simplify Profile status UI https://github.com/mozilla/mozillians/pull/1436
* Groups grid UI enhancements https://github.com/mozilla/mozillians/pull/1426/
* (Mentoring) [Bug 847911](https://bugzilla.mozilla.org/show_bug.cgi?id=847911) Create a view with all vouched mozillians
* (Mentoring) [Bug 1333373](https://bugzilla.mozilla.org/show_bug.cgi?id=1333373) Redesign footer based on new brand identity
* Automated ServiceNow ticket creation for SSO Dashboard deployments
* Implement API Key Support on behalf of RPs
* SSO Dashboard: Implement low- and med-risk alert UI https://github.com/mozilla-iam/sso-dashboard/issues/130
* Slack for Community access (next iteration of the current manual _NDA Pilot_)
* WorkDay/CIS integration
* [SSO Dashboard] (bugfix) Run access-proxy in front of SSO dashboard (https://github.com/mozilla-iam/sso-dashboard/issues/107)
* Move AirMo to 'hosted Auth0 Lock'
* SSO Dashboard improvements
   - UX: user favorites https://github.com/mozilla-iam/sso-dashboard/issues/92 / frequently used #98
   - Fix SSO with ParSys properties
* [AUTH0 LOCK] _Prototype new technology stack_
   - Sign Up UI design #67 
   - Decide on technology stack for Front-end and AWS Lambda (backend)
   - Create backlog items
* [Bug 1373894](https://bugzilla.mozilla.org/show_bug.cgi?id=1373894): Potential XSS in Mozillians.org

## Logistics
* Consulted: https://github.com/mozilla-iam/iam-project-backlog/issues/173
* Out of Office:  @m-branson, @akatsoulas, @gdestuynder out for most of the sprint; @viorelaioia for a couple of days; 15 AUG is a public holiday in Bavaria
* CoSS share: @comzeradd focus mostly on CoSS
