### ISSUE TITLE
Sprint 14 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#198]
## Prioritized Themes
1. RP Cutovers, Sprint 14 bit
1. Mozillians.org  _Q2 OKR Leftovers_
1. Initiate work on _SSO Dashboard Q3 Goal_
1. SSH Federated Access (multi-sprint) #169 
1. Mozillians.org Infrastructure _debt repayment_
1. ~IAM **Q3** OKR (Share a G Suite document with a Mozillians.org group): _Crushing the Boulder_~ (deprioritized _stop starting and start finishing_ on the many other open ends we currently have)

### Details
1. RP Cutover: [Migration Plan](https://docs.google.com/spreadsheets/d/1VLwh2A9qbaRqByj7BYbnziWQLL_DdjemAiwT4_0OebE/edit)
    - [ ] Group 3 (Cutover coordinated independently) #133 
    - [ ] Decom RPs that won't migrate #61
1. Mozillians.org  _Q2 OKR Leftovers_
    - [ ] AWS metadata proxy https://github.com/mozilla/parsys/issues/217
    - [ ] Make Mozillians.org group updates just-in-time (already **DONE**?)
    - [ ] CIS Whitelist group: enroll more people
    - [ ] [Bug 1391632](https://bugzilla.mozilla.org/show_bug.cgi?id=1391632) UI to invite users to groups can mislead users to add the wrong users
    - [ ] userinfo endpoint does not return https://github.com/mozilla-iam/cis_functions/issues/25
    - [ ] (from #iam) architecture review to clarify some of the future of the service from a docs perspective
    - [ ] (from #iam) I'd hate to have to have a FAQ "I can't login to taskcluster" "A: go to mozillians and set your t-shirt size.  people without t-shirt sizes are prohibited"
    - [ ] (attn @LeoMcA) Make Discourse compatible with the 'cis_whitelist' group. Goal: Replace access to https://discourse.mozilla.org/c/iam/internal with _Q2 OKR mechanics_)
1. SSO Dashboard Q3 Goal: **User alerts**
    - [ ] SSO Dashboard: Implement low- and med-risk alert UI https://github.com/mozilla-iam/sso-dashboard/issues/130 (_"Your version of Firefox is out of date"_)
    - [ ] (bug) Fetch user full name from mozillians.org https://github.com/mozilla-iam/sso-dashboard/issues/158
1. SSH Federated Access (multi-sprint) #169 
    - [ ] Finalize project documentation (https://mana.mozilla.org/wiki/display/SECURITY/Auth0+and+SSH)
    - [ ] POC Client-side 
    - [ ] POC Server-side
    - [ ] POC IT Deploy with original groups
1. Mozillians.org  _Infrastructure Cleanup_
    - [ ] Finish off CDN work
1. QA Engineering
    - [ ] Automate CIS tests - Verify that updates to a mozillians profile are visible in auth0 #199 
1. Other things
    - [ ] (optional) Fix Lock (library) upgrade issues https://github.com/mozilla-iam/auth0-deploy/issues/143

## For mental sanity: Other InfoSec Work
1. Accommodate Auth0 OIDC Conformant mode requirements #171
    - [ ] Create a list of RPs to decide next steps (test, coordinate with owners, switchover)
1. "Second Opinion" #79 
    - [ ] Productionalize

## For mental sanity: Other ParSys Work
1. [ ] [CoSS](https://github.com/mozilla/coss/) Sprint 14 https://github.com/mozilla/coss/issues/285
1. [ ] [Discourse] https://github.com/mozilla/discourse/milestone/3 
1. [ ] [Bug 138342](https://bugzilla.mozilla.org/show_bug.cgi?id=1383642) - OVH servers are down

## Unplanned Scope
**Note:** please add any unplanned scope that you worked on here.

## Out of Scope / Later Items
Themes which are not **yet** slated for delivery
- _**Q3** OKR Crushing the Boulder_
   - Review and update Sprints 2017Q3 (Infosec) https://github.com/mozilla-iam/iam-project-backlog/issues/173
   - Solution architecture ([data classification](https://docs.google.com/a/mozilla.com/spreadsheets/d/1STSiHgdKFZtf1AsHe-YJ8DYGJNIlAXaKfVN6Cqi8hSQ/edit?usp=sharing))
   - Stories (aka GitHub issues)
   - Pairing plan
- [ParSys] Kick off Kubernetes pilot project
- Mozillians.org Binary search: get it to DONE-DONE
- Pre-plan LDAP to CIS connector (publisher) @andrewkrug 
- Now that we have _Q2 OKR_ in PROD (**defer until CIS Whitelist is removed**):
   - Slack for Community access (next iteration of the current manual _NDA Pilot_)
   - TechSpeakers Discourse group
   - Reps Discourse group
* [Fix bug 1201027] Simplify Profile status UI https://github.com/mozilla/mozillians/pull/1436
* Groups grid UI enhancements https://github.com/mozilla/mozillians/pull/1426/
* (Mentoring) [Bug 847911](https://bugzilla.mozilla.org/show_bug.cgi?id=847911) Create a view with all vouched mozillians
* (Mentoring) [Bug 1333373](https://bugzilla.mozilla.org/show_bug.cgi?id=1333373) Redesign footer based on new brand identity
* Automated ServiceNow ticket creation for SSO Dashboard deployments
* Implement API Key Support on behalf of RPs
* WorkDay/CIS API-based integration
* Move AirMo to 'hosted Auth0 Lock'
* SSO Dashboard improvements
   - (bugfix) Run access-proxy in front of SSO dashboard (https://github.com/mozilla-iam/sso-dashboard/issues/107)
   - UX: user favorites https://github.com/mozilla-iam/sso-dashboard/issues/92 / frequently used #98
   - Fix SSO with ParSys properties
* [AUTH0 LOCK] _Prototype new technology stack_
   - Sign Up UI design #67 
   - Decide on technology stack for Front-end and AWS Lambda (backend)
   - Create backlog items
* [Bug 1373894](https://bugzilla.mozilla.org/show_bug.cgi?id=1373894): Potential XSS in Mozillians.org

## Logistics
* Consulted: https://github.com/mozilla-iam/iam-project-backlog/issues/173
* Out of Office:  @hmitsch on vacation in week 21-25 AUG
* CoSS share: @comzeradd focus mostly on CoSS
