### ISSUE TITLE
Sprint 15 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#201]
## Prioritized Themes
1. RP Cutovers, Sprint 15 bit - final segment?
1. Mozillians.org  _Q2 OKR Leftovers_
1. Work on _SSO Dashboard Q3 Goal_
1. SSH Federated Access (multi-sprint) #169 
1. IAM **Q3** OKR (Share a G Suite document with a Mozillians.org group): Start getting HR data into CIS

### Details
1. RP Cutover
1. *Getting Q2 OKR to Production*
    * The RP we choose is *Discourse*
    * Add GitHub authentication to Mozillians.org
    * Enforcement of MFA (GitHub MFA and LDAP)
    * Write Auth0 rule to display CIS info on user endpoint
    * Not send CIS groups for passwordless and Google
    * Proper communications (and how to fix it)
    * Extend CIS_whitelist to include all of IT & ParSys
    * CIS Whitelisting is extended to the *Mozillians NDA Group*
    * Only for Discourse: send passwordless users to an info page telling them that they need to log in through Github
    * Identify how to handle the remaining applications moving forward (Moderator, Reps Portal), with a focus on AirMo (because it is is not a ParSys property)
    - [ ] (getting to done-done) AWS metadata proxy https://github.com/mozilla/parsys/issues/217
    - [ ] [Bug 1391632](https://bugzilla.mozilla.org/show_bug.cgi?id=1391632) UI to invite users to groups can mislead users to add the wrong users (@akatsoulas has a quick fix idea)
    - [ ] (from #iam) architecture review to clarify some of the future of the service from a docs perspective
    - [ ] (**BLOCKER**) T-Shirt size mandatory on Mozillians.org-CIS data flow
       - Use Case #1: (from #iam) I'd hate to have to have a FAQ "I can't login to taskcluster" "A: go to mozillians and set your t-shirt size.  people without t-shirt sizes are prohibited" 
       - Use Case #2: also blocks Discourse using iam for nda category (unless we want to tell everyone in the nda group to set their t-shirt size while setting up github mfa)
       - check with @akatsoulas @johngian in next TechAlignment
1. SSO Dashboard Q3 Goal: **User alerts**
    - [ ] SSO Dashboard: Implement low- and med-risk alert UI https://github.com/mozilla-iam/sso-dashboard/issues/130 (_"Your version of Firefox is out of date"_)
    - [ ] (**blocked** until alerts are merged) Fetch user full name from mozillians.org https://github.com/mozilla-iam/sso-dashboard/issues/158 : Merge, QA on stage and then deploy to prod
1. SSH Federated Access (multi-sprint) #169 
    - [ ] Finalize project documentation (https://mana.mozilla.org/wiki/display/SECURITY/Auth0+and+SSH)
    - [ ] POC Client-side 
    - [ ] POC Server-side
    - [ ] POC IT Deploy with original groups
1. QA Engineering
    - [ ] Manage to get the CIS tests and RP login tests running in InfoSec infrastructure (https://github.com/mozilla-iam/iam-project-backlog/issues/202)
    - [ ] Implement login tests for RPs that were recently migrated to auth0: Phonebook , MozDataColective , Service-now prod 
1. Q3 OKR: HRIS-CIS Integration
   - [ ] Storage of HR data to the CIS Identity Vault
   - [ ] Heads-up to Jen H. about the work we would desire from her to work towards G Suite integration

## For mental sanity: Other InfoSec Work
1. Accommodate Auth0 OIDC Conformant mode requirements #171
    - [ ] Create a list of RPs to decide next steps (test, coordinate with owners, switchover)
1. "Second Opinion" #79 
    - [ ] Productionalize

## For mental sanity: Other ParSys Work
1. [ ] [CoSS](https://github.com/mozilla/coss/) Sprint 15 https://github.com/mozilla/coss/issues/351
1. [ ] [Discourse] https://github.com/mozilla/discourse/milestone/4
    - Sync groups from IAM in prod
    - Add tagging for add-on support requests
    - Create process for post-sprint future
    - Write excellent contribution documentation 
    - Vimeo CSP https://github.com/mozilla/parsys/issues/225
1. [ ] [Reps] [Bug 1394736] ICS export specifies wrong event time
1. [ ] [Infra] [Reps bug] Remo spamming emails https://github.com/mozilla/parsys/issues/221
1. [ ] [Infra] [Bug 138342](https://bugzilla.mozilla.org/show_bug.cgi?id=1383642) - OVH servers are down
1. [ ] [Infra] ParSys AWS mid-year budgeting https://github.com/mozilla/parsys/issues/203
1. [x] [Infra] Fix reps cache url https://github.com/mozilla/parsys/issues/188
1. [ ] [Infra] Add mozillians admin role https://github.com/mozilla/parsys/issues/216
1. [x] [Infra] [Bug 1390083] Add Discourse and Moderator to internal/public statuspages

## Unplanned Scope
**Note:** please add any unplanned scope that you worked on here.
- [ ] [Bug 1397868](https://bugzilla.mozilla.org/show_bug.cgi?id=1397868) mozilla-django-oidc is a member of mozilla GitHub account

## Out of Scope / Later Items
Themes which are not **yet** slated for delivery
- Fix Lock (library) upgrade issues https://github.com/mozilla-iam/auth0-deploy/issues/143
- _**Q3** OKR Crushing the Boulder_
   - Review and update Sprints 2017Q3 (Infosec) https://github.com/mozilla-iam/iam-project-backlog/issues/173
   - Solution architecture ([data classification](https://docs.google.com/a/mozilla.com/spreadsheets/d/1STSiHgdKFZtf1AsHe-YJ8DYGJNIlAXaKfVN6Cqi8hSQ/edit?usp=sharing))
   - Stories (aka GitHub issues)
   - Pairing plan
- [ParSys] Kick off Kubernetes pilot project
- Mozillians.org Binary search: get it to DONE-DONE
- Pre-plan LDAP to CIS connector (publisher) @andrewkrug 
- Now that we have _Q2 OKR_ in PROD (**defer until CIS Whitelist is removed**):
   - Slack for Community access (next iteration of the current manual _NDA Pilot_)
   - TechSpeakers Discourse group
   - Reps Discourse group
* [Fix bug 1201027] Simplify Profile status UI https://github.com/mozilla/mozillians/pull/1436
* Groups grid UI enhancements https://github.com/mozilla/mozillians/pull/1426/
* (Mentoring) [Bug 847911](https://bugzilla.mozilla.org/show_bug.cgi?id=847911) Create a view with all vouched mozillians
* (Mentoring) [Bug 1333373](https://bugzilla.mozilla.org/show_bug.cgi?id=1333373) Redesign footer based on new brand identity
* Automated ServiceNow ticket creation for SSO Dashboard deployments
* Implement API Key Support on behalf of RPs
* WorkDay/CIS API-based integration
* Move AirMo to 'hosted Auth0 Lock'
* SSO Dashboard improvements
   - (bugfix) Run access-proxy in front of SSO dashboard (https://github.com/mozilla-iam/sso-dashboard/issues/107)
   - UX: user favorites https://github.com/mozilla-iam/sso-dashboard/issues/92 / frequently used #98
   - Fix SSO with ParSys properties
* [AUTH0 LOCK] _Prototype new technology stack_
   - Sign Up UI design #67 
   - Decide on technology stack for Front-end and AWS Lambda (backend)
   - Create backlog items
* [Bug 1373894](https://bugzilla.mozilla.org/show_bug.cgi?id=1373894): Potential XSS in Mozillians.org

## Logistics
* Out of Office:  @hmitsch traveling on 06, 08, 12 SEPT
* CoSS share: @comzeradd focus mostly on CoSS, @akatsoulas at a conference this week, @johngian hopefully back next week

**Comment by gdestuynder** [comment]
Write Auth0 rule to display CIS info on user endpoint => https://github.com/mozilla-iam/auth0-deploy/pull/144

**Comment by gdestuynder** [comment]
Enforcement of MFA (GitHub MFA and LDAP) => GH: https://github.com/mozilla-iam/auth0-deploy/pull/145 LDAP: https://github.com/mozilla-iam/auth0-deploy/pull/146

**Comment by gdestuynder** [comment]
Not send CIS groups for passwordless and Google => https://github.com/mozilla-iam/cis/pull/77

**Comment by gdestuynder** [comment]
Workaround to fix `updated_at` openidconnect spec issue https://github.com/mozilla-iam/auth0-deploy/pull/147
