### ISSUE TITLE
SSO Dashboard

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/iam-project-backlog#23]
Develop a dashboard that can replace the current Okta dashboard.

MVP - populate dashboard with icons/links for each SSO property (e.g. SmartSheet, Gmail, Mana)
Enhanced - display user-specific security information (e.g. login from a new country, Awareness Training status)

See https://github.com/mozilla-iam/sso-dashboard
and https://github.com/mozilla-iam/sso-dashboard/projects/1

* [AUTH0 DASHBOARD] _Drive the dashboard infrastructure to DONE-DONE_ 
   - [x] Development of core Dashboard [functionality](https://github.com/mozilla-iam/sso-dashboard/projects/1)
   - [x] #99 SSO Dashboard Development Environment 
   - [X] #65 Fix workaround for adding new emails to be compatible with SSO dashboard
   - [x]  #78 Production Deployment of SSO Dashboard 
   - [x]  #83 Create Cloudformation to Deploy Multi-Region sso.dashboard
   - [x]  #84 Vanity urls served by sso.mozilla.com
* [AUTH0 DASHBOARD]_UI Development_ 
   - [x] #53 SSO Dashboard UX/UI - Design
   - [x] #92 Request Open Design Support for Icons 
   - [x] #103 SSO Dashboard Implement initial version of UI design

**Comment by andrewkrug** [comment]
Production goes live tomorrow

**Comment by andrewkrug** [comment]
@hmitsch 

When do we consider this card to have reached MVP?  I know for example we will not have this feature for all hands:

#98 SSO Dashboard Favorite Apps - UI Design

Should we remove it so we can define the working release as done?

**Comment by andrewkrug** [comment]
Also updated #65 as it was marked done.

**Comment by hmitsch** [comment]
@andrewkrug yes, lets remove the open things and make sure they are in the backlog. This issue should definitely be closed. Thank you!

**Comment by andrewkrug** [comment]
Removed 96, 97, and 98 from this card.  Alert/UI was in progress.  @hmitsch All other items are in fact in backlog.

**Comment by hmitsch** [comment]
Thank you!
-- 
Henrik Mitsch
Senior Manager Participation Systems

irc: hmitsch | skype: henrik.mitsch
Cell: +49 176 99351302
