### ISSUE TITLE
User profile synchronization service between LDAP and Auth0

### ISSUE THREAD

**Issue by tyearns** [mozilla-iam/iam-project-backlog#57]
Design POC service for pushing user account profile updates from LDAP to Auth0
- Validate POC functionality - In-Progress
- Component testing has been completed
- Artifacts available on Git (get URL from Kang)

**Comment by gdestuynder** [comment]
## Component testing references
(same thing, its been moved twice - feel free to close #31 if that's clearer)
https://github.com/mozilla-iam/mozilla-iam/issues/7
https://github.com/mozilla/iam-project-backlog/issues/31

## Main artifact

Tested and selected solution:

On LDAP group change, send an API call to auth0 for user:update_user such as:

`curl -H "Authorization: Bearer ..." -X PATCH  -H "Content-Type: application/json" -d '{"user_metadata":{"group":["group_a", "group_b"]}}' https://auth-dev.mozilla.auth0.com/api/v2/users/ad%7CMozilla-LDAP-Dev%7Cgdestuynder`

Where the `group` is in user.user_metadata (the Auth0 API forbids writing directly to `user.*` data structure).

Then, a rule catches all logins and delegation requests (thus group update requests) to rewrite the groups membership entirely:

```
function (user, context, callback) {
  user.user_metadata = user.user_metadata || {};
  //Note: not checks being made here as we do want this to be undefined or empty array if
  //user.user_metadata.group is undefined or empty.
  user.groups = user.user_metadata.group;
  callback(null, user, context);
}
```

**Comment by gdestuynder** [comment]
## Todo
- [ ] Implement above integration rule into https://github.com/mozilla-iam/auth0-deploy for any data filled in `user.user_metadata.*`
- [ ] Implement trigger LDAP-side (https://github.com/mozilla-iam/ldap-postgres-reference) when the user profile is updated.
- [ ] Use trigger to send API call documented above (`https://auth-dev.mozilla.auth0.com/api/v2/users/...`) for all data from the user profile that much be integrated into `user.user_metadata.*` and thus (after the rule runs) into `user.*`.

## High level event flow
- User profile is updated in SQL/LDAP
- Trigger is activated
- New user profile is sent to the Auth0 API and stored in a metadata field
- Auth0 rule is triggered when API call finishes (automatically)
- Auth0 rule copies all fields under the metadata field (ie the new user profile) into the real user profile
- User profile in auth0 now contains both new user profile information and any existing auth0 profile information. All duplicate fields are replaced by the most recent version of the data, i.e. data coming from LDAP.

**Comment by gdestuynder** [comment]
I believe this supersedes https://github.com/mozilla/iam-project-backlog/issues/3 (ie that https://github.com/mozilla/iam-project-backlog/issues/3 can be closed)

**Comment by hmitsch** [comment]
Story declared obsolete in _Q2 OKR Grooming Session_.
