### ISSUE TITLE
Sign Up UI Design (v1)

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#67]
For UI design of the IAM flow, I'll start with the Mozillians Sign Up screens. This will be an initial design based on new and evolving Mozilla brand guidelines. This will provide early direction for the IAM prototype that @comzeradd is implementing.

**Tasks to complete:**

- [x] **Interface with Brand Team re: design review process**
- [x] **Attend Portland Design Sprint to familiarize with new brand & begin building UI library**
- [x] **Mozillians Header UI**
- [x] **Mozillians Footer UI**
- [x] **Email Entry UI**
- [x] **Sign Up Form UI**
- [x] **Email Sent Success UI**
- [x] **Form Field UI states (hover, active)**
- [x] **Re-captcha UI**

**Comment by m-branson** [comment]
Adding tasks to this issue for Sprint 4:

- [ ] **Interface with Brand Team re: design review process**
- [ ] **Attend Portland Design Sprint to familiarize with new brand & begin building UI library*
- [ ] **Mozillians Header UI**
- [ ] **Mozillians Footer UI**
- [ ] **Email Entry UI**
- [ ] **Success Message UI**
- [ ] **Sign Up Form UI**
- [ ] **User Dashboard UI**

**Comment by mbransn** [comment]
Making progress on mozillians.org sign up UI. As this will be hosted on mozillians.org, we are applying mozillians blue (updated brand blue) to the UI and have the mozillians header in view during the sign up process.

In addition to mobile versions of this flow I will continue to work through: UI for form states (hover, active); re-captcha UI; and search states (hover, active).

**Log In / Sign Up screen:**

![mozillians-login-signup](https://cloud.githubusercontent.com/assets/18686986/25507908/9d1b6d3a-2b63-11e7-83ae-fc08897b3142.jpg)

**Sign Up email sent:**

![mozillians-signup-email](https://cloud.githubusercontent.com/assets/18686986/25507913/a35ef644-2b63-11e7-9206-422470ff6247.jpg)

**Sign Up form:**

![mozillians-signup-form](https://cloud.githubusercontent.com/assets/18686986/25507914/a7ea55a0-2b63-11e7-83c7-582410f817ad.jpg)

**Comment by mbransn** [comment]
@comzeradd can you remind me how much we can affect the UI for reCAPTCHA? Is it limited or can we affect the basic functionality that we see here?

![photo_2017-04-27_16-00-35](https://cloud.githubusercontent.com/assets/18686986/25508003/301bb9a0-2b64-11e7-9660-0eb7b75ed4bc.jpg)

**Comment by comzeradd** [comment]
Not much. It just gives you some preset options: Theme (Dark or Light) and Size (Normal, Compact).

What we could do is utilize the new [invisible recaptcha](https://developers.google.com/recaptcha/docs/invisible). We should still account for the regular recaptcha, because machine learning won't have always successful results. But at least the vast majority of our users won't see the recaptcha at all.

**Comment by mbransn** [comment]
Awesome, invisible recaptcha sounds like a great way to go. I will account for the compact recaptcha V2 size (300x80) in our sign up form though. 👍

**Comment by mbransn** [comment]
Closing, continuing iteration and prep for implementation in #125 during Sprint 7.
