### ISSUE TITLE
Log In/Sign Up User Testing Results Implementation

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#71]
**Overview of actionable results from [Sprint 3 Log In/Sign Up user testing](https://github.com/mozilla/iam-project-backlog/issues/68).**

Looking to implement these in Sprint 4 via [Sign Up UI Design](https://github.com/mozilla/iam-project-backlog/issues/67) or within the code prototype being built by @comzeradd. Will note in each task where they will be implemented.

- [x] **Explore location of Mozilla logo:** #67 
Users primarily assume the Mozilla logo will return them to the homepage, not the Mozillians header. Possibly implement a Mozilla Logo/Mozillians lock up or place Mozilla logo in footer, making Mozillians primary messaging. 
- [x] **Update 'Join Mozillians' CTA language to 'Sign Up for Mozillians’:** #67 
Users look for the words 'sign up' to initiate a new account and read ‘Join’ as an opportunity to become a member of a group or club once they've registered for the site. 
- [x] **Review need for password creation on Mozillians sign up form:** #67 
Users were expecting an opportunity to create a password here. If not on the form, how do we make it a prominent option after account creation?
- [x] **Implement a link to Passwordless wiki info at the Auth0 Lock log in screen:** (code prototype)
Users expressed interest in understanding what passwordless was and how/why they would use it instead of a password. 
- [x] **Explore providing an integrated avatar & user name with menu icon.** #67 
Users expressed interest in seeing their info highlighted in the header upon successful log in/sign up.

**Comment by mbransn** [comment]
These updates have been made to the latest version of the wireframes and will be visually shared via #67 during Sprint 5.
